CXX = g++
CXXFLAGS	= -std=c++17 -Wall

all: TicTacoToe.cpp 

clean: 
	rm TicTacToe.o

TicTacoToe.cpp:
	$(CXX) $(CXXFLAGS) TicTacToe.cpp -o TicTacToe.o

#TicTacoToe.o:
# 	$(CXX) $(CXXFLAGS) -c TicTacToe.cpp
